...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -13,8 +13,14 @@ ___x_cmd_ffmpeg(){
 
 }
 
+x pkg xbin exec ffmpeg "$@"
+
 ___x_cmd_ffmpeg_origin(){
-    x pkg xbin exec ffmpeg "$@"
+    if ! ___x_cmd_pkg_xbin_init ffmpeg ___x_cmd_ffmpeg_origin; then
+        x:error "Fail to pkg_xbin_init ffmpeg"
+        return 1
+    fi
+    ___x_cmd_ffmpeg_origin "$@"
 }
 
 ___x_cmd_ffmpeg_show(){
